## Append samples you want in your CSV to this file as resources ##
resources:
- k8ssandra.io_v1alpha1_k8ssandracluster.yaml
- _v1alpha1_stargate.yaml
- k8ssandra.io_v1alpha1_replicatedsecret.yaml
- medusa_v1alpha1_MedusaTask.yaml
- medusa_v1alpha1_medusabackup.yaml
- medusa_v1alpha1_medusabackupjob.yaml
- medusa_v1alpha1_medusarestorejob.yaml
- medusa_v1alpha1_medusabackupschedule.yaml
- control_v1alpha1_k8ssandratask.yaml
- medusa_v1alpha1_medusaconfiguration.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
