apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/k8ssandra/cass-operator/config/deployments/default?ref=master

images:
  - name: k8ssandra/cass-operator
    newTag: 34648fd3
