apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../cass-operator/config/deployments/default
# - github.com/k8ssandra/cass-operator/config/deployments/default?ref=v1.14.0

components:
  - ../../components/cass-operator-image-config