apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/k8ssandra/cass-operator/config/deployments/default?ref=v1.10.0

images:
  - name: k8ssandra/cass-operator
    newTag: v1.10.0