apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k8ssandra-operator
resources:
  - ../../default
images:
  - name: cr.k8ssandra.io/k8ssandra/k8ssandra-operator
    newTag: v1.12.0
