resources:
- github.com/k8ssandra/k8ssandra-operator/config/default?ref=main

patchesJson6902:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/1/value
      value: "false"
  target:
    group: apps
    kind: Deployment
    name: k8ssandra-operator
    version: v1

images:
- name: k8ssandra/k8ssandra-operator
  newTag: latest
